---
title: "Working at Home in the Puget Sound"

format: 
  dashboard:
    orientation: columns
theme: [sandstone, theme/custom.scss]
logo: images/RegionalGem2016.png
logo-alt: "Puget Sound Regional Council Lego with 4 boxes representing the counties"
editor_options: 
  chunk_output_type: console
output-dir: docs
output-file: index.html
---

```{r}
#| label: load-packages
#| message: false
library(tidyverse)
library(gt)
library(psrcplot)
library(dplyr)
library(scales)
library(quarto)

overall_df <- read_csv("data/telecommuteornot_summary_trend.csv")


hybrid_df<-read_csv("data/telecommute_summary_trend.csv")

work_at_home_23_all<-hybrid_df%>%filter(survey_year=='2023')%>%
  filter(telecommute_status=='Fully At Home')%>%select(prop)%>%pull

work_at_home_23_hybrid<-hybrid_df%>%filter(survey_year=='2023')%>%
  filter(telecommute_status== 'Hybrid')%>%select(prop)%>%pull

```

# Work at Home Overall

## Column

### Row


### Always At Home Worker Share (2023)

::: {.valuebox icon="house-fill" color="#73CFCB" title="Always at Home Worker Share (2023)"}

`{r}  label_percent(accuracy = 1.0)(work_at_home_23_all)`
:::



### Row
```{r}
#| title: Working At Home Share Trend

trend<-interactive_line_chart(overall_df, y='prop', x='survey_year', fill='telecommute_freq_cond') 
trend
```


## Column
### Row



::: {.valuebox icon="house" color="#A9D46E" title="Hybrid Worker Share (2023)"}

`{r}  label_percent(accuracy = 1.0)(work_at_home_23_hybrid)`
:::

### Row
```{r}
#| title: Working At Home Patterns Trend

hybrid_df<-hybrid_df%>%mutate(survey_year=factor(survey_year))%>%mutate(telecommute_status=forcats::fct_reorder(telecommute_status, -prop))
inter<-interactive_column_chart(hybrid_df, y='prop', x='survey_year', fill='telecommute_status', xlabel='Work Location Status', ylabel='Worker Share', pos='stack')

inter
```

# Demographics

# Geography

# Travel Patterns
